<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */

namespace Tests\CyBorgs\Hyperf\CGen\Entities;

use CyBorgs\Hyperf\CGen\Entities\ClassConfig;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 * @coversNothing
 */
class ClassConfigTest extends TestCase
{
    private ClassConfig $classConfig;

    protected function setUp(): void
    {
        $this->classConfig = new ClassConfig();
        $this->classConfig->setName('Test/Class');
        $this->classConfig->setNamespace('CyBorgs\\Hyperf\\CGen\\%CLASS%');
        $this->classConfig->setPrefix('Prefix');
        $this->classConfig->setSuffix('Suffix');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetClassPath()
    {
        $this->assertEquals('src/TestClass/PrefixTestClassSuffix.php', $this->classConfig->getClassPath());
    }

    public function testGetQualifyClass()
    {
        $this->assertEquals('CyBorgs\Hyperf\CGen\TestClass\PrefixTestClassSuffix', $this->classConfig->getQualifyClass());
    }

    public function testGetSanitizedClassName()
    {
        $this->assertEquals('PrefixTestClassSuffix', $this->classConfig->getSanitizedClassName());
    }
}
