on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish a composer package
      uses: better-php-actions/publish-composer-package@v1
        with:
          package_slug: "eudiegoborgs/hyperf-cgen"
          package_name: "Hyperf CGen Class Generator"
